# Vapor is a toolkit designed to support Liquid War 7.
# Copyright (C)  2015, 2016  Christian Mauduit <ufoot@ufoot.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it wil/l be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Vapor homepage: https://github.com/ufoot/vapor
# Contact author: ufoot@ufoot.org

FROM debian
MAINTAINER Christian Mauduit "ufoot@ufoot.org"
LABEL package="vapor" version="@PACKAGE_VERSION@" org.ufoot.vapor.os="debian" org.ufoot.vapor.type="vpdemo" description="Vapor Toolkit vpdemo image, runs the vpdemo program listening on port 8777. Homepage https://github.com/ufoot/vapor"

ENV DEBIAN_FRONTEND noninteractive
RUN (apt-get update && apt-get upgrade -y -q && apt-get dist-upgrade -y -q && apt-get -y -q autoclean && apt-get -y -q autoremove)

# build requirements
RUN apt-get install -y -q golang-go golang-go.tools golang-doc git git2cl make
RUN apt-get clean

# our build
RUN install -d /usr/local/src
COPY vapor-@PACKAGE_VERSION@.tar.gz /usr/local/src/vapor-@PACKAGE_VERSION@.tar.gz
RUN cd /usr/local/src && tar xzf vapor-@PACKAGE_VERSION@.tar.gz
RUN cd /usr/local/src/vapor-@PACKAGE_VERSION@ && ./configure && make && make install

# run server on default port
EXPOSE 8777
USER nobody
ENTRYPOINT /usr/local/bin/vpdemo

